"""
Base strategy interface.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from datetime import datetime
from typing import Optional
import pandas as pd


class SignalType(Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    symbol: str
    signal_type: SignalType
    strength: float  # 0.0 to 1.0
    price: float
    timestamp: datetime
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    metadata: Optional[dict] = None


class BaseStrategy(ABC):
    """Abstract base class for trading strategies."""

    def __init__(self, name: str, params: Optional[dict] = None):
        self.name = name
        self.params = params or {}

    @abstractmethod
    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate technical indicators for the strategy.

        Args:
            df: DataFrame with OHLCV data

        Returns:
            DataFrame with added indicator columns
        """
        pass

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, symbol: str) -> Signal:
        """
        Generate a trading signal based on the data.

        Args:
            df: DataFrame with OHLCV data and indicators
            symbol: The trading symbol

        Returns:
            Signal object with buy/sell/hold recommendation
        """
        pass

    def should_enter(self, signal: Signal) -> bool:
        """Determine if we should enter a position based on the signal."""
        return signal.signal_type == SignalType.BUY and signal.strength >= 0.5

    def should_exit(self, signal: Signal) -> bool:
        """Determine if we should exit a position based on the signal."""
        return signal.signal_type == SignalType.SELL and signal.strength >= 0.5

    def calculate_position_size(
        self,
        signal: Signal,
        portfolio_value: float,
        max_position_pct: float = 0.05,
    ) -> float:
        """
        Calculate position size based on signal strength and risk parameters.

        Args:
            signal: The trading signal
            portfolio_value: Current portfolio value
            max_position_pct: Maximum position size as percentage of portfolio

        Returns:
            Dollar amount to allocate to this position
        """
        base_size = portfolio_value * max_position_pct
        return base_size * signal.strength
